name: mecdis_soporte_remoto_shell
description: Mec-Dis Soporte Remoto (UI SHELL) - Lanzador y diagnóstico para backend externo.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mecdis_logo.png
